### ISSUE TITLE
tox.cmdline() fails on 3.0.0rc2 but works in 2.9.1

### ISSUE THREAD

**Issue by Jerhaad** [tox-dev/tox#773]
We use this functionality in a lot of our tools and I'm not seeing anything about this in the changelog/documentation.

```bash
$ python
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tox
>>> tox.cmdline()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: main() missing 1 required positional argument: 'args'
>>>
```

```bash
$ pip list
pip (9.0.1)
pluggy (0.6.0)
py (1.5.2)
setuptools (38.5.2)
six (1.11.0)
tox (3.0.0rc2)
virtualenv (15.1.0)
wheel (0.30.0)
```

Mac OS X 10.12.6

**Comment by gaborbernat** [comment]
@Jerhaad thanks for the report, seems we should import ``run_main`` instead of ``main`` here https://github.com/tox-dev/tox/blob/master/tox/__init__.py#L87

**Comment by obestwalter** [comment]
Thanks @Jerhaad - good, I start to believe in the power of the rc :)

@gaborbernat - you assigned yourself, so I'll check when this is fixed and release the hopefully last rc. I would also suggest to not merge anything else then anymore until 3.0 is released.
